wife(X, prince_charles).
uncle(timothy_laurence, james).
aunt(X, princess_charlotte).
grandmother(camilla_parker_bowles, archie_harrison).
grandmother(X, archie_harrison).
husband(X, princess_anne).
sibling(X, prince_louis).
mother(X, prince_andrew).
niece(X, princess_anne).
sister(X, james).
wife(queen_elizabethII, mike_tindall).
grandparent(X, prince_louis).
daughter(X, princess_anne).
son(X, meghan_markle).
son(X, sarah_ferguson).
nephew(X, meghan_markle).
grandson(X, prince_charles).
grandchild(X, princess_diana).
husband(mark_phillips, princess_anne).
brother(X, zara_tindall).
uncle(X, princess_eugenie).
grandchild(X, queen_elizabethII).
father(X, autumn_phillips).
child(mike_tindall, mark_phillips).
